sudo: false
language: python
python:
  - '3.3'
  - '3.4'
  - '3.5'
  - "pypy"
  - "pypy3"
install:
  - pip install pip pybuilder coveralls --upgrade
  - pyb install_dependencies -X
script:
  - pyb -X run_unit_tests
after_success:
  - coveralls --verbose
